"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {BookOpen,Compass,Gamepad2,Sparkles,X} from "lucide-react";
import {RelationshipGraph,type NetworkDepth} from "@/components/relationship-graph";
import {RelationshipChallengeGame} from "@/components/relationship-challenge-game";
import {useProgress} from "@/components/progress-provider";
import {characters} from "@/data/discoveries";
import {journeyNodes} from "@/data/journey";
import {relationshipAchievementDefinitions,relationshipTypeLabels,relationships} from "@/data/relationships";
import type {Relationship,RelationshipType} from "@/lib/types";
import styles from "./connections.module.scss";

type FamilyFilter="all"|"bond"|"duty"|"mission"|"political";
const families:{id:FamilyFilter;label:string;types:RelationshipType[]}[]=[
 {id:"all",label:"All",types:[]},{id:"bond",label:"Bond",types:["family","marriage","friendship"]},{id:"duty",label:"Bhakti / Duty",types:["devotion","service","protector"]},{id:"mission",label:"Guidance / Mission",types:["teacher","guidance","messenger"]},{id:"political",label:"Conflict / Political",types:["alliance","opposition"]},
];
const depths:{id:NetworkDepth;label:string}[]=[{id:"first",label:"First degree"},{id:"expanded",label:"Expand network"},{id:"whole",label:"Whole network"}];
function incident(edge:Relationship,id:string){return edge.fromCharacterId===id||edge.toCharacterId===id;}

export default function ConnectionsPage(){
 const {progress,recentRelationshipUnlocks,acknowledgeRelationshipUnlocks}=useProgress();const [mode,setMode]=useState<"explore"|"play">("explore"),[family,setFamily]=useState<FamilyFilter>("all"),[focus,setFocus]=useState("hanuman"),[depth,setDepth]=useState<NetworkDepth>("first"),[selectedIds,setSelectedIds]=useState<string[]>([]);
 useEffect(()=>{if(recentRelationshipUnlocks.length){const timer=setTimeout(acknowledgeRelationshipUnlocks,5000);return()=>clearTimeout(timer);}},[recentRelationshipUnlocks,acknowledgeRelationshipUnlocks]);
 const unlocked=useMemo(()=>relationships.filter(r=>progress.unlockedRelationships.includes(r.id)),[progress.unlockedRelationships]);const locked=relationships.filter(r=>!progress.unlockedRelationships.includes(r.id));const filtered=family==="all"?unlocked:unlocked.filter(edge=>families.find(item=>item.id===family)!.types.includes(edge.type));
 const shown=useMemo(()=>{if(depth==="whole")return filtered;const first=filtered.filter(edge=>incident(edge,focus));if(depth==="first")return first;const neighbors=new Set(first.flatMap(edge=>[edge.fromCharacterId,edge.toCharacterId]));return filtered.filter(edge=>neighbors.has(edge.fromCharacterId)||neighbors.has(edge.toCharacterId));},[depth,filtered,focus]);
 const unlockedCharacters=characters.filter(character=>progress.unlockedCharacters.includes(character.name));const selected=selectedIds.map(id=>relationships.find(edge=>edge.id===id)).filter((edge):edge is Relationship=>Boolean(edge));
 function changeFocus(id:string){setFocus(id);setDepth("first");setSelectedIds([]);}function selectRelations(items:Relationship[]){setSelectedIds(items.map(item=>item.id));}
 return <main className="page-shell"><div className={styles.shell}><header className={styles.hero}><div><p className="eyebrow">Sacred bonds · living knowledge</p><h1 className="page-title">Threads of the epic</h1><p className="page-intro">Begin with one character, follow the bonds revealed through the journey, and expand the network when you are ready.</p></div><div className={styles.count}><strong>{unlocked.length}/{relationships.length}</strong><span>connections discovered</span></div></header>
 {recentRelationshipUnlocks.length>0&&<div className={styles.unlock}><Sparkles/><div><strong>{recentRelationshipUnlocks.length} new {recentRelationshipUnlocks.length===1?"connection":"connections"} revealed</strong><p>Your journey has expanded the network.</p></div></div>}
 <nav className={styles.modeTabs} aria-label="Connection modes"><button className={mode==="explore"?styles.active:""} onClick={()=>setMode("explore")}><Compass size={17}/>Explore Network</button><button className={mode==="play"?styles.active:""} onClick={()=>setMode("play")}><Gamepad2 size={17}/>Play Connections</button></nav>
 {mode==="explore"?<><section className={styles.exploreControls}><label>Character<select value={focus} onChange={e=>changeFocus(e.target.value)}>{unlockedCharacters.map(character=><option key={character.id} value={character.id}>{character.name}</option>)}</select></label><div><span>Relationship filters</span><div className={styles.segmented}>{families.map(item=><button key={item.id} className={family===item.id?styles.segmentActive:""} onClick={()=>{setFamily(item.id);setSelectedIds([]);}}>{item.label}</button>)}</div></div><div><span>Network depth</span><div className={styles.segmented}>{depths.map(item=><button key={item.id} className={depth===item.id?styles.segmentActive:""} onClick={()=>{setDepth(item.id);setSelectedIds([]);}}>{item.label}</button>)}</div></div></section>
 <div className={`${styles.networkWorkspace} ${selected.length?styles.hasDetail:""}`}><section className={styles.networkPanel}>{shown.length||focus?<RelationshipGraph relationships={shown} focusId={focus} depth={depth} unlockedCharacterNames={progress.unlockedCharacters} unlockedRelationshipIds={progress.unlockedRelationships} selectedIds={selectedIds} onSelect={selectRelations} onFocus={changeFocus}/>:<p className="p-8">No discovered connections match this view.</p>}</section>{selected.length>0&&<RelationshipDetail relationships={selected} onClose={()=>setSelectedIds([])}/>}</div>
 {!shown.length&&<p className={styles.emptyHint}>No relationship in this family has been discovered around {characters.find(c=>c.id===focus)?.name}. Try another filter or continue the journey.</p>}{locked.length>0&&<section className={styles.veiled}><p className="eyebrow">Still veiled</p><div>{locked.slice(0,3).map(edge=><article key={edge.id}><strong>? → ?</strong><span>{edge.eventId}</span></article>)}</div><p>{locked.length} relationships remain hidden until their journey events are completed. <Link href="/journey/hanuman">Continue the journey →</Link></p></section>}
 </>:<><RelationshipChallengeGame/><section className={styles.achievementSection}><p className="eyebrow">Knowledge achievements</p><div className={styles.achievementGrid}>{relationshipAchievementDefinitions.map(item=><article key={item.name}><strong>{progress.achievements.includes(item.name)?"✦":"○"} {item.name}</strong><p>{item.description}</p></article>)}</div></section></>}
 </div></main>;
}

function RelationshipDetail({relationships,onClose}:{relationships:Relationship[];onClose:()=>void}){const first=relationships[0],from=characters.find(c=>c.id===first.fromCharacterId)!,to=characters.find(c=>c.id===first.toCharacterId)!,events=Array.from(new Set(relationships.map(item=>item.eventId))),sources=Array.from(new Set(relationships.flatMap(item=>item.sources)));return <aside className={styles.detailPanel} aria-label="Relationship detail"><button className={styles.closeDetail} onClick={onClose} aria-label="Close relationship details"><X/></button><p className="eyebrow">Discovered connection</p><h2>{from.name} {first.directional?"→":"↔"} {to.name}</h2><div className={styles.detailSection}><span>Relationships</span><div className={styles.typeChips}>{relationships.map(item=><strong key={item.id}>{relationshipTypeLabels[item.type]}</strong>)}</div></div><div className={styles.detailSection}><span>Meaning</span>{relationships.map(item=><p key={item.id}>{from.name} {item.label} {to.name}.</p>)}</div><div className={styles.detailSection}><span>Discovered in</span>{events.map(event=>{const node=journeyNodes.find(item=>item.id===event);return node?<Link key={event} href={`/journey/hanuman/${node.slug}`}><BookOpen size={15}/>{event} · {node.title}</Link>:<p key={event}>{event}</p>;})}</div><div className={styles.detailSection}><span>Sources</span><div className={styles.sourceChips}>{sources.map(source=><strong key={source}>{source}</strong>)}</div></div><div className={styles.characterLinks}><Link href={`/characters/${from.id}`}>View {from.name}</Link><Link href={`/characters/${to.id}`}>View {to.name}</Link></div></aside>}
