"use client";

import {ArrowRight,Check,HeartPulse,Mountain,RotateCcw} from "lucide-react";
import {NodeSceneCard} from "@/components/node-scene-card";
import {useProgress} from "@/components/progress-provider";
import {activityById} from "@/data/encounter-activities";
import {medicinalHerbs} from "@/data/herbs";
import {rescueBriefSteps} from "@/data/chapter-seven";
import type {JourneyNode,PredictionChoiceActivity} from "@/lib/types";
import styles from "@/components/chapter-seven-experience.module.scss";

function activity(id:string){return activityById(id) as PredictionChoiceActivity;}
function RescueBrief({node}:{node:JourneyNode}){const current=rescueBriefSteps.findIndex(step=>step.nodeId===node.id);return <aside className={styles.brief} aria-labelledby="rescue-brief-title"><header><span><HeartPulse/> Rescue Brief</span><strong id="rescue-brief-title">Understand the mission before moving fast</strong></header><div>{rescueBriefSteps.map((step,index)=><article key={step.nodeId} data-state={index<current?"complete":index===current?"current":"future"}><span>{index<current?<Check/>:index+1}</span><section><small>{step.label}</small><p><b>Need</b>{step.need}</p>{index===current&&<><p><b>Instruction</b>{step.instruction}</p><p><b>Uncertain</b>{step.uncertain}</p><p><b>Action</b>{step.action}</p></>}</section></article>)}</div></aside>}

const targeted:Record<string,Record<string,string>>={
 "C7-HFH01-NEED":{status:"This person may be important, but what specific capability does the mission require right now?",proximity:"Proximity helps only when the nearby person can perform the necessary journey."},
 "C7-HFH01-SERVANT":{rama:"Authority matters, but the responder still needs the exact movement, strength, and reliability the mission demands.",jambavan:"Jāmbavān supplies judgment and direction. Who can execute the distant physical mission?",lakshmana:"The person closest to the need is not automatically capable of answering it."},
 "C7-HFH02-ADAPT":{guess:"Urgency is high, but what happens if the wrong herb is brought back?",empty:"The mission cannot be completed empty-handed. Is there another way to preserve certainty?",delay:"Precision matters, but time is also part of the crisis. What solution preserves both?"},
 "C7-HFH02-REPAIR":{guess:"Guessing protects speed while sacrificing medical certainty.",delay:"Endless searching protects an ideal of precision while ignoring the urgent lives at stake.",empty:"Returning nothing preserves no usable path to treatment."},
 "C7-HFH03-PATIENT":{army:"That describes the first crisis. Which detail places this later scene after Rāvaṇa’s spear strike?",same:"This resembles the earlier mission, but the immediate patient and cause have changed."},
 "C7-HFH03-DIRECTION":{jambavan:"Jāmbavān directs the first medicinal mission. Who examines Lakṣmaṇa in this later crisis?",hanuman:"Hanumān transports urgently; his strength does not replace medical expertise."},
 "C7-HFH03-ROLES":{solo:"This erases Suṣeṇa’s medical authority. Which role actually belongs to Hanumān?",repeat:"The similar journey hides a different patient, cause, and medical director.",symbol:"The mountain carries medicines; it does not replace diagnosis and treatment."},
};

function Choice({id}:{id:string}){const {progress,selectPrediction}=useProgress(),item=activity(id),value=progress.predictionChoices[id],correct=value===item.canonicalAnswer;return <section className={styles.panel} aria-labelledby={`${id}-title`}><small>{item.title}</small><h3 id={`${id}-title`}>{item.prompt}</h3><div className={styles.choices}>{item.choices.map(option=><button type="button" key={option.id} aria-pressed={value===option.id} onClick={()=>selectPrediction(id,option.id)}><span>{value===option.id?<Check/>:"·"}</span>{option.label}</button>)}</div>{value&&<div className={correct?styles.good:styles.repair}><strong>{correct?item.canonicalReveal:"Re-evaluate the mission"}</strong><p>{correct?item.explanation:targeted[id]?.[value]??item.explanation}</p>{!correct&&<span><RotateCcw/> Choose again after comparing the need and capability.</span>}</div>}</section>}
function correct(progress:ReturnType<typeof useProgress>["progress"],id:string){return progress.predictionChoices[id]===activity(id).canonicalAnswer}
function Action({ready,label,onComplete}:{ready:boolean;label:string;onComplete:()=>void}){return <div className={styles.action}><button type="button" disabled={!ready} onClick={onComplete}>{label}<ArrowRight/></button>{!ready&&<small>Commit to a judgment, inspect the consequence, and repair the reasoning.</small>}</div>}

function HFH01({onComplete}:{onComplete:()=>void}){const {progress}=useProgress(),ids=["C7-HFH01-NEED","C7-HFH01-SERVANT","C7-HFH01-WISDOM"],ready=ids.every(id=>correct(progress,id));return <><div className={styles.intro}><span>Identify the needed servant</span><h2 id="chapter-seven-action-title">What does the crisis require?</h2><p>Begin with the mission rather than the most powerful name. Jāmbavān’s wisdom lies in recognizing where a particular strength can become useful.</p></div>{ids.map(id=><Choice key={id} id={id}/>)}<Action ready={ready} label="Accept the rescue mission" onComplete={onComplete}/></>}
function HerbKnowledge(){return <details className={styles.herbs}><summary><Mountain/> Four named medicines · Yuddha Kāṇḍa 74</summary><p>The names preserve source knowledge; botanical memorization is not required to progress.</p><dl>{medicinalHerbs.map(([name,purpose])=><div key={name}><dt>{name}</dt><dd>{purpose}</dd></div>)}</dl></details>}
function HFH02({onComplete}:{onComplete:()=>void}){const {progress}=useProgress(),mission=correct(progress,"C7-HFH02-MISSION"),adapt=correct(progress,"C7-HFH02-ADAPT"),repair=correct(progress,"C7-HFH02-REPAIR"),consequence=correct(progress,"C7-HFH02-CONSEQUENCE"),attempted=Boolean(progress.predictionChoices["C7-HFH02-ADAPT"]);return <><div className={styles.intro}><span>Adapt</span><h2 id="chapter-seven-action-title">Preserve precision when identification fails</h2><p>The herbs are specific and the need is urgent. The problem is not whether Hanumān is strong enough; it is how strength can preserve certainty without losing time.</p></div><HerbKnowledge/><Choice id="C7-HFH02-MISSION"/>{mission&&<Choice id="C7-HFH02-ADAPT"/>}{attempted&&!adapt&&<section className={styles.constraint}><span>Compare the constraints</span><div><b>Precision</b><b>Time</b><b>Certainty</b></div><Choice id="C7-HFH02-REPAIR"/></section>}{adapt&&!progress.predictionChoices["C7-HFH02-REPAIR"]&&<Choice id="C7-HFH02-REPAIR"/>}{repair&&<Choice id="C7-HFH02-CONSEQUENCE"/>}<Action ready={mission&&adapt&&repair&&consequence} label="Return with the medicinal peak" onComplete={onComplete}/></>}
function BriefComparison(){return <section className={styles.comparison} aria-labelledby="two-rescues"><h3 id="two-rescues">Two similar journeys · two distinct missions</h3><article><small>First rescue · Yuddha 74</small><p><b>Patients</b> Rāma, Lakṣmaṇa, and many in the army</p><p><b>Cause</b> Indrajit’s Brahmā-related weapon</p><p><b>Direction</b> Jāmbavān</p></article><article><small>Second rescue · Yuddha 101</small><p><b>Patient</b> Lakṣmaṇa</p><p><b>Cause</b> Rāvaṇa’s spear</p><p><b>Direction</b> Suṣeṇa, physician</p></article></section>}
function HFH03({onComplete}:{onComplete:()=>void}){const {progress}=useProgress(),ids=["C7-HFH03-PATIENT","C7-HFH03-DIRECTION","C7-HFH03-ROLES"],ready=ids.every(id=>correct(progress,id));return <><div className={styles.intro}><span>Distinguish</span><h2 id="chapter-seven-action-title">What is different this time?</h2><p>A familiar journey can conceal a different patient, cause, instruction chain, and medical authority. Inspect the differences before acting.</p></div><BriefComparison/>{ids.map((id,index)=><div key={id}>{index===0||correct(progress,ids[index-1])?<Choice id={id}/>:null}</div>)}{ready&&<section className={styles.finale}><small>Chapter VII · Strength becomes lifesaving service</small><h3>Service preserves the mission.</h3><p>Jāmbavān recognized the need → Hanumān answered → identification failed → strength became adaptation → the army was restored → Suṣeṇa directed a second, distinct rescue.</p><strong>Next · Chapter VIII — Mission Fulfilled</strong><span>Saving the army gives way to completing the larger mission.</span></section>}<Action ready={ready} label="Carry service toward mission fulfilled" onComplete={onComplete}/></>}

export function ChapterSevenExplore({node,onComplete}:{node:JourneyNode;onComplete:()=>void}){return <div className={styles.experience}><RescueBrief node={node}/><div className={styles.scene}><NodeSceneCard scene={node.scene} revealed={false} observation/></div>{node.id==="HFH-01"?<HFH01 onComplete={onComplete}/>:node.id==="HFH-02"?<HFH02 onComplete={onComplete}/>:<HFH03 onComplete={onComplete}/>}</div>}
