"use client";

import Link from "next/link";
import {useMemo,useState} from "react";
import {ArrowLeft,Award,BookMarked,Check,HeartHandshake,LockKeyhole} from "lucide-react";
import {CharacterPortrait} from "@/components/character-portrait";
import {SacredObjectCard} from "@/components/sacred-object-card";
import {characters,relationships} from "@/data/discoveries";
import {journeyNodes} from "@/data/journey";
import {warNodes} from "@/data/war";
import {herbsNodes} from "@/data/herbs";
import {finaleNodes} from "@/data/finale";
import {useProgress} from "@/components/progress-provider";
import {characterNameById} from "@/data/character-ids";
import {relationshipTypeLabels} from "@/data/relationships";
import {characterAnswerIsCorrect,characterChallengesFor,characterFieldIsUnlocked,characterFieldsFor,characterKnowledgeProfileFor,characterKnowledgeProgress,characterRoleIsKnown,characterSourceReviewGaps} from "@/data/character-knowledge";
import {sacredObjects} from "@/data/encounter-activities";
import {meetingMemories,meetingMemoryNames,meetingNodes} from "@/data/meeting";
import {searchNodes} from "@/data/search";
import {searchChapterNodes,searchMemories,searchMemoryNames} from "@/data/search";
import {crossingMemories,crossingMemoryNames,crossingNodes} from "@/data/crossing";
import type {CharacterProfileField,CharacterProfileSection} from "@/lib/types";
import {encounterHref} from "@/lib/journey-navigation";
import {orderedSourceRefs} from "@/lib/source-readiness";

const allJourneyNodes=[...meetingNodes,...searchNodes,...journeyNodes,...warNodes,...herbsNodes,...finaleNodes];

type Tab="overview"|"family"|"guidance"|"connections"|"journey"|"events"|"objects"|"sources"|"challenge";
const tabLabels:Record<Tab,string>={overview:"Overview",family:"Family",guidance:"Guidance",connections:"Connections",journey:"Journey",events:"Key Events",objects:"Sacred Objects",sources:"Sources",challenge:"Complete the Character"};
const tabSections:Partial<Record<Tab,CharacterProfileSection>>={overview:"overview",family:"family",guidance:"guidance",connections:"connections",journey:"journey",events:"events",objects:"objects",sources:"sources"};
const sectionLabels:Partial<Record<CharacterProfileSection,string>>={overview:"Identity & meaning",family:"Family",guidance:"Guidance & learning",connections:"Relationship knowledge",journey:"Journey & places",events:"Key events",objects:"Sacred objects",sources:"Source record"};
const familyOrder=["Parents","Siblings","Spouse","Children"] as const;
const provenance=(field:CharacterProfileField)=>field.unlockMethod==="autoOnCharacterDiscovery"?"Foundational · character discovery":field.unlockMethod==="autoOnJourneyNode"?`Journey · ${field.unlock.kind==="journey"?field.unlock.nodeId:"milestone"}`:field.unlockMethod==="autoOnJourneyComplete"?"Journey completion":field.unlockMethod==="connectionsChallenge"?"Connections":field.unlockMethod==="characterChallenge"?"Character Challenge":field.unlockMethod==="sacredObjectDiscovery"?"Sacred Object discovery":field.unlockMethod==="sourceExploration"?"Source exploration":"Pending source review";
const unlockHint=(field:CharacterProfileField)=>field.unlockMethod==="autoOnCharacterDiscovery"?"Reveals when this character is discovered.":field.unlockMethod==="autoOnJourneyNode"?`Knowledge becomes available at ${field.unlock.kind==="journey"?field.unlock.nodeId:"a Journey milestone"}.`:field.unlockMethod==="autoOnJourneyComplete"?"Reveals when the Hanumān Journey is complete.":field.unlockMethod==="connectionsChallenge"?"Discover through Connections.":field.unlockMethod==="characterChallenge"?"Discover through Complete the Character.":field.unlockMethod==="sacredObjectDiscovery"?"Discover through the Sacred Object interaction.":field.unlockMethod==="sourceExploration"?"Source exploration required.":"Not yet available in V1.";

function KnowledgeField({field,revealed,characterId,characterUnlocked,onOpenChallenge}:{field:CharacterProfileField;revealed:boolean;characterId:string;characterUnlocked:(id:string)=>boolean;onOpenChallenge:()=>void}){
 let nodeId:string|undefined;
 if(field.unlock.kind==="journey")nodeId=field.unlock.nodeId;
 if(field.unlock.kind==="object"){const objectId=field.unlock.objectId;nodeId=sacredObjects.find(item=>item.id===objectId)?.discoveryNode;}
 const node=nodeId?allJourneyNodes.find(item=>item.id===nodeId):undefined;
 return <article className={`knowledge-field ${revealed?"revealed":"concealed"}`}>
  <div className="knowledge-field-label">{revealed?<Check size={14}/>:<LockKeyhole size={14}/>}<span>{field.label}</span></div>
  {revealed?<>{field.relatedCharacterId&&characterUnlocked(field.relatedCharacterId)?<Link href={`/characters/${field.relatedCharacterId}`}>{field.value} →</Link>:<strong>{field.value}</strong>}<small>{field.sourceStatus} · {orderedSourceRefs(field.sources).map(item=>item.source).join(" · ")} · <b>{provenance(field)}</b></small>{node&&<Link className="knowledge-unlock-action" href={encounterHref(node.slug,"character",characterId)}>Return to {node.id} · {node.title} →</Link>}</>:<><strong>Undiscovered</strong><small>{unlockHint(field)}</small>{field.unlockMethod==="characterChallenge"?<button className="knowledge-unlock-action" onClick={onOpenChallenge}>Open Character Challenge →</button>:field.unlockMethod==="connectionsChallenge"?<Link className="knowledge-unlock-action" href="/connections">Open Connections →</Link>:node?<Link className="knowledge-unlock-action" href={encounterHref(node.slug,"character",characterId)}>Go to {node.id} →</Link>:null}</>}
 </article>;
}

function FamilyMember({field,revealed,characterUnlocked}:{field:CharacterProfileField;revealed:boolean;characterUnlocked:(id:string)=>boolean}){
 const related=field.relatedCharacterId?characters.find(item=>item.id===field.relatedCharacterId):undefined;
 const portraitVisible=Boolean(revealed&&related?.portrait&&field.relatedCharacterId&&characterUnlocked(field.relatedCharacterId));
 const content=<><div className={`family-medallion ${portraitVisible?"":"veiled"}`}>{portraitVisible&&related?.portrait?<CharacterPortrait name={related.name} portrait={related.portrait} usage="medallion"/>:<LockKeyhole size={18}/>}</div><div><small>{field.label}</small><strong>{revealed?field.value:"Undiscovered relative"}</strong><span>{revealed?`${field.sourceStatus} · ${orderedSourceRefs(field.sources).map(item=>item.source).join(" · ")}`:unlockHint(field)}</span></div></>;
 return revealed&&field.relatedCharacterId&&characterUnlocked(field.relatedCharacterId)?<Link className="family-member" href={`/characters/${field.relatedCharacterId}`}>{content}</Link>:<div className={`family-member ${revealed?"":"locked"}`}>{content}</div>;
}

export function CharacterDetail({id}:{id:string}){
 const {progress,hydrated,answerCharacter}=useProgress();
 const [tab,setTab]=useState<Tab>("overview"),[selected,setSelected]=useState<Record<string,string>>({}),[showAllMemories,setShowAllMemories]=useState(false);
 const character=characters.find(item=>item.id===id)!,profile=characterKnowledgeProfileFor(id);
 const knowledge=characterKnowledgeProgress(id,progress),fields=characterFieldsFor(id),challenges=characterChallengesFor(id),reviewGaps=characterSourceReviewGaps[id]??[];
 const roleKnown=characterRoleIsKnown(id,progress);
 const qualityKnown=fields.some(field=>(field.label==="Key qualities"||field.label==="Supporting quality"||field.label==="Meaning")&&characterFieldIsUnlocked(field,progress));
 const unlocked=(characterId:string)=>progress.unlockedCharacters.includes(characterNameById[characterId]??"");
 const allRelations=useMemo(()=>relationships.filter(relation=>relation.fromCharacterId===id||relation.toCharacterId===id),[id]);
 const relationGroups=useMemo(()=>{
  const records=allRelations.filter(relation=>progress.unlockedRelationships.includes(relation.id));
  return Object.values(records.reduce((groups,relation)=>{const other=relation.fromCharacterId===id?relation.toCharacterId:relation.fromCharacterId;(groups[other]??=[]).push(relation);return groups;},{} as Record<string,typeof records>));
 },[allRelations,id,progress.unlockedRelationships]);
 const tabs=(Object.keys(tabLabels) as Tab[]).filter(item=>item==="challenge"?challenges.length>0:item==="connections"?allRelations.length>0:fields.some(field=>field.section===tabSections[item]));
 const labelForTab=(item:Tab)=>profile.depth==="encounter"&&item==="journey"?"Encounter":tabLabels[item];
 const activeTab=tabs.includes(tab)?tab:tabs[0];
 function openChallenge(){setTab("challenge");requestAnimationFrame(()=>document.querySelector<HTMLElement>(".character-challenge-shell h2")?.focus());}
 if(!hydrated)return <main className="page-shell">Loading your collection…</main>;
 if(!unlocked(id)){const unlockNode=allJourneyNodes.find(node=>node.id===character.unlockNodeId);return <main className="page-shell"><div className="mx-auto max-w-3xl"><Link className="character-back" href="/characters"><ArrowLeft size={16}/> Character collection</Link><section className="character-detail-locked"><LockKeyhole size={34}/><p className="eyebrow">Undiscovered character</p><h1 className="font-display text-5xl">This story is still hidden</h1><p>Reach <strong>{character.unlockEncounter}</strong> to reveal this character record.</p>{unlockNode&&<Link className="cta-primary" href={encounterHref(unlockNode.slug,"character",id)}>Go to {unlockNode.id}</Link>}</section></div></main>;}

 const activeSection=tabSections[activeTab],sectionFields=activeSection?fields.filter(field=>field.section===activeSection):[],relatedObjects=sacredObjects.filter(object=>object.relatedCharacters.includes(character.name));
 const memoryEntries=[
  ...meetingMemoryNames.map((name,index)=>({chapter:"Chapter I",name,memory:meetingMemories[index],node:meetingNodes[index]})),
  ...searchMemoryNames.map((name,index)=>({chapter:"Chapter II",name,memory:searchMemories[index],node:searchChapterNodes(journeyNodes)[index]})),
  ...crossingMemoryNames.map((name,index)=>({chapter:"Chapter III",name,memory:crossingMemories[index],node:crossingNodes(journeyNodes)[index]})),
 ];
 const familyFields=fields.filter(field=>field.section==="family");
 const latestMemory=[...memoryEntries].reverse().find(entry=>progress.achievements.includes(entry.name));
 const rememberedNode=[...allJourneyNodes].reverse().find(node=>node.characters.includes(character.name)&&(progress.revealedScenes.includes(node.id)||[...progress.meetingCompletedNodes,...progress.searchCompletedNodes,...progress.completedNodes,...progress.warCompletedNodes,...progress.herbsCompletedNodes,...progress.finaleCompletedNodes].includes(node.id)));
 const rememberedField=fields.find(field=>(field.section==="journey"||field.section==="events")&&!field.label.includes("Journey encounter")&&characterFieldIsUnlocked(field,progress));
 const memoryUnlockNodeId=rememberedField?.unlock.kind==="journey"?rememberedField.unlock.nodeId:undefined;
 const memoryLinkNode=rememberedNode??(memoryUnlockNodeId?allJourneyNodes.find(node=>node.id===memoryUnlockNodeId):undefined);
 return <main className="page-shell"><div className="mx-auto max-w-6xl">
  <Link className="character-back" href="/characters"><ArrowLeft size={16}/> Character collection</Link>
  <header className={`character-detail-hero ${knowledge.state==="Complete"&&knowledge.total>0?"complete":""}`}><div className="character-detail-portrait">{character.portrait&&<CharacterPortrait name={character.name} portrait={character.portrait} usage="detail"/>}{knowledge.state==="Complete"&&<span className="portrait-complete-ring" aria-hidden="true"/>}</div><div><p className="eyebrow">{character.group} · Tier {profile.depth==="major"?"A":profile.depth==="supporting"?"B":"C"} {profile.depth}</p><h1 className="page-title">{character.name}</h1><p className="character-detail-script">{character.sanskrit}</p><p className="character-transliteration">{character.transliteration}</p><p className="page-intro">{roleKnown?character.role:character.group}</p><aside className="character-current-memory"><small>Remembered in the journey</small><strong>{id==="hanuman"&&latestMemory?latestMemory.name:rememberedNode?rememberedNode.title:rememberedField?rememberedField.label:"A story still unfolding"}</strong><span>{id==="hanuman"&&latestMemory?latestMemory.memory:rememberedNode?rememberedNode.completionTakeaway||rememberedNode.excerpt:rememberedField?rememberedField.value:`Continue the journey to learn more about ${character.name}.`}</span><Link href={memoryLinkNode?encounterHref(memoryLinkNode.slug,"character",id):"/journey"}>{memoryLinkNode?"Return to this moment":"Return to the journey"} →</Link></aside>{qualityKnown&&<div className="character-qualities mt-6">{character.qualities.slice(0,2).map(quality=><span key={quality}>{quality}</span>)}</div>}{knowledge.total>0?<div className="knowledge-summary"><div><strong>{knowledge.percentage}%</strong><span>{knowledge.state==="Complete"?<><Award size={14}/> V1 Profile Complete</>:"Hanumān Journey knowledge"}</span></div><div className="knowledge-meter"><i style={{width:`${knowledge.percentage}%`}}/></div><small>{knowledge.unlocked} of {knowledge.total} supported facts revealed in this content scope</small></div>:<div className="knowledge-summary pending"><span>Expanded dossier awaiting source verification</span></div>}</div></header>
  <nav className="character-tabs" aria-label="Character dossier sections">{tabs.map(item=><button key={item} className={activeTab===item?"active":""} aria-pressed={activeTab===item} onClick={()=>setTab(item)}>{labelForTab(item)}{item==="challenge"&&challenges.some(challenge=>!characterAnswerIsCorrect(progress,challenge.id))&&<i/>}</button>)}</nav>
  {activeSection&&activeTab!=="family"&&activeTab!=="connections"&&activeTab!=="objects"&&<div className="knowledge-sections"><section className="character-detail-panel"><div className="character-section-title"><BookMarked/><div><p className="eyebrow">{knowledge.sections[activeSection].unlocked} / {knowledge.sections[activeSection].total} revealed</p><h2>{sectionLabels[activeSection]}</h2></div></div><div className="knowledge-field-grid">{sectionFields.map(field=><KnowledgeField key={field.id} field={field} revealed={characterFieldIsUnlocked(field,progress)} characterId={id} characterUnlocked={unlocked} onOpenChallenge={openChallenge}/>)}</div>{activeTab==="sources"&&reviewGaps.length>0&&<div className="source-review-gaps"><p className="eyebrow">Awaiting source verification · excluded from V1 completion</p><ul>{reviewGaps.map(gap=><li key={gap}>{gap}</li>)}</ul></div>}</section></div>}
  {activeTab==="objects"&&<div className="knowledge-sections"><section className="character-detail-panel"><div className="character-section-title"><BookMarked/><div><p className="eyebrow">{relatedObjects.filter(object=>progress.discoveredObjects.includes(object.id)).length} / {relatedObjects.length} discovered</p><h2>Sacred objects</h2></div></div><div className="character-object-grid">{relatedObjects.map(object=><SacredObjectCard key={object.id} object={object} discovered={progress.discoveredObjects.includes(object.id)} mode="standard" showSources/>)}</div></section></div>}
  {activeTab==="family"&&<section className="family-tree character-detail-panel"><div className="character-section-title"><BookMarked/><div><p className="eyebrow">{knowledge.sections.family.unlocked} / {knowledge.sections.family.total} revealed</p><h2>Known family</h2></div></div><div className="family-tree-root"><div className="family-person central"><strong>{character.name}</strong><small>Character</small></div><span/></div><div className="family-groups">{familyOrder.map(group=>{const groupFields=familyFields.filter(field=>(field.familyGroup??(field.label.toLowerCase().includes("father")?"Parents":field.label==="Spouse"?"Spouse":"Children"))===group);return groupFields.length?<section key={group}><h3>{group}</h3><div>{groupFields.map(field=><FamilyMember key={field.id} field={field} revealed={characterFieldIsUnlocked(field,progress)} characterUnlocked={unlocked}/>)}</div></section>:null})}</div>{reviewGaps.length>0&&<p className="family-review-note">Only family ties verified in the current approved V1 source record contribute to completion. Additional relations remain in source review.</p>}</section>}
  {activeTab==="connections"&&<section className="character-detail-panel"><div className="character-section-title"><HeartHandshake/><div><p className="eyebrow">Directional · multi-type</p><h2>Discovered connections</h2></div></div>{sectionFields.length>0&&<div className="knowledge-field-grid">{sectionFields.map(field=><KnowledgeField key={field.id} field={field} revealed={characterFieldIsUnlocked(field,progress)} characterId={id} characterUnlocked={unlocked} onOpenChallenge={openChallenge}/>)}</div>}{relationGroups.length?<div className="character-relationship-list">{relationGroups.map(group=>{const other=group[0].fromCharacterId===id?group[0].toCharacterId:group[0].fromCharacterId;return <article key={other}><div className="relationship-type-row">{group.map(relation=><span key={relation.id}>{relationshipTypeLabels[relation.type]}</span>)}</div>{group.map(relation=><p key={relation.id}><strong>{characterNameById[relation.fromCharacterId]}</strong> {relation.label} <strong>{characterNameById[relation.toCharacterId]}</strong></p>)}{unlocked(other)&&<Link href={`/characters/${other}`}>Open {characterNameById[other]} →</Link>}</article>})}</div>:<p className="character-empty">Continue the journey or complete a character challenge to reveal this network.</p>}</section>}
  {activeTab==="challenge"&&<section className="character-challenge-shell"><div><p className="eyebrow">Knowledge practice</p><h2 className="font-display" tabIndex={-1}>Complete the Character</h2><p>Each answer reveals supported knowledge and may confirm a connection in the living network.</p></div>{challenges.map(challenge=>{const answered=progress.characterChallengeAnswers[challenge.id],correct=characterAnswerIsCorrect(progress,challenge.id),pick=selected[challenge.id]??answered;return <article className={`character-challenge ${correct?"complete":""}`} key={challenge.id}><div className="character-challenge-heading"><span>{challenge.type.replaceAll("-"," ")}</span>{correct&&<strong><Check size={15}/> Knowledge revealed</strong>}</div><h3>{challenge.prompt}</h3><p>{challenge.context}</p><div className="character-challenge-options">{challenge.options.map(option=><button disabled={correct} onClick={()=>setSelected(values=>({...values,[challenge.id]:option.id}))} className={pick===option.id?"selected":""} aria-pressed={pick===option.id} key={option.id}><span>{option.id.toUpperCase()}</span>{option.label}</button>)}</div>{pick&&!correct&&<button className="cta-primary" onClick={()=>answerCharacter(challenge.id,pick)}>Reveal this knowledge</button>}{answered&&!correct&&<p className="challenge-feedback wrong">That answer does not fit this record yet. Read the clue and try again.</p>}{correct&&<p className="challenge-feedback correct">{challenge.explanation}</p>}</article>})}</section>}
  {id==="hanuman"&&<section className="character-memory-trail" id="memory-trail" aria-labelledby="memory-trail-title" data-expanded={showAllMemories}>
   <div className="character-memory-heading"><div><p className="eyebrow">Chapters I–III · lived knowledge</p><h2 id="memory-trail-title">Memory trail</h2></div><p>The story record appears when the moment is revealed. Three mastery stars add a deeper reflection.</p></div>
   <ol>{memoryEntries.map((entry,index)=>{const node=entry.node,deep=progress.achievements.includes(entry.name),storyKnown=deep||progress.revealedScenes.includes(node.id)||[...progress.meetingCompletedNodes,...progress.searchCompletedNodes,...progress.completedNodes].includes(node.id);return <li className={storyKnown?"revealed":"locked"} key={entry.name}><span className="memory-step" aria-hidden="true">{storyKnown?<Check size={17}/>:index+1}</span><div><small>{entry.chapter} · {node.id} · {node.title}</small><strong>{deep?entry.name:storyKnown?"Story remembered":"Story not yet revealed"}</strong><p>{deep?entry.memory:storyKnown?node.completionTakeaway||node.excerpt:`Continue ${node.title} to reveal this story moment.`}</p>{storyKnown&&!deep&&<small>Deeper insight available with three mastery stars.</small>}</div><Link href={encounterHref(node.slug,"character",id)} aria-label={`${storyKnown?"Revisit":"Continue"} ${node.title}`}>{storyKnown?"Revisit":"Continue"}<span aria-hidden="true"> →</span></Link></li>})}</ol>
   <button className="character-memory-toggle" aria-expanded={showAllMemories} onClick={()=>setShowAllMemories(value=>!value)}>{showAllMemories?"Show fewer memories":"Show all memories"}</button>
  </section>}
  {knowledge.total>0&&<section className={`completion-summary ${knowledge.state==="Complete"?"is-complete":""}`}><div><Award/><p><strong>{knowledge.state==="Complete"?"V1 Profile Complete":"Knowledge by category"}</strong><span>{knowledge.state==="Complete"?"All supported Hanumān Journey knowledge has been discovered.":"Only facts supported in the current content scope count here."}</span></p></div><dl>{Object.entries(knowledge.sections).filter(([,count])=>count.total>0).map(([section,count])=><div key={section}><dt>{sectionLabels[section as CharacterProfileSection]}</dt><dd>{count.unlocked}/{count.total}</dd></div>)}</dl></section>}
 </div></main>;
}
