"use client";

import {useMemo,useState} from "react";
import {ArrowRight,Check,Footprints,Lightbulb,RefreshCcw,Shield} from "lucide-react";
import {useProgress} from "@/components/progress-provider";
import {crossingTrailEntries} from "@/data/crossing";
import type {JourneyNode} from "@/lib/types";
import styles from "@/components/crossing-experience.module.scss";

type Choice={id:string;label:string;feedback:string};
type CrossingAction={verb:string;question:string;evidence:string[];choices:Choice[];correct:string;repair:string;resolution:string;secondStep?:{prompt:string;choices:Choice[];correct:string}};
const actions:Record<string,CrossingAction>={
 "HJ-04":{verb:"Commit",question:"What makes Hanumān ready to leave the shore?",evidence:["Sampāti’s testimony directs the search toward Laṅkā.","Rāma’s ring carries recognizable trust.","Jāmbavān has recalled Hanumān’s reach, judgment, and devotion.","The mission requires finding Sītā and returning with knowledge."],choices:[{id:"integrate",label:"Unite destination, evidence, token, capability, and return",feedback:"This makes the leap a complete mission rather than a display of power."},{id:"power",label:"Rely on strength alone",feedback:"Strength enables departure, but what preserves the mission when the situation changes?"},{id:"wait",label:"Wait until every uncertainty disappears",feedback:"The destination and messenger are established. Total certainty is not available before action."}],correct:"integrate",repair:"Choose the evidence that joins purpose, proof, capability, and return.",resolution:"The Search Board becomes a launch plan. Hanumān commits fully and the crossing begins."},
 "HJ-05":{verb:"Assess",question:"What kind of interruption is rising from the ocean?",evidence:["The mountain interrupts the direct route.","It offers a place to rest.","Its approach carries welcome rather than seizure.","Rāma’s mission remains urgent."],choices:[{id:"attack",label:"Attack before the route closes",feedback:"What evidence shows hostility? Interruption alone does not establish attack."},{id:"ignore",label:"Ignore the mountain completely",feedback:"This preserves speed, but misses the welcoming character of the approach."},{id:"stop",label:"Stop and remain as long as hospitality requires",feedback:"This honors hospitality, but abandons the urgency carried from the shore."},{id:"honor",label:"Acknowledge the offer warmly, then continue",feedback:"This preserves respect and mission momentum together."}],correct:"honor",repair:"Remove the assumption that every interruption is hostile; weigh welcome against urgency.",resolution:"Hanumān honors Maināka without surrendering momentum."},
 "HJ-06":{verb:"Adapt",question:"How should Hanumān answer a challenge that expands whenever he does?",evidence:["Surasā blocks the route and demands passage through her mouth.","Each increase in Hanumān’s size is matched by a wider opening.","Continued escalation spends strength without creating passage."],choices:[{id:"grow",label:"Continue increasing size and power",feedback:"The challenge scales with him. Bigger has produced more escalation, not passage."},{id:"strike",label:"Destroy the obstacle immediately",feedback:"The encounter has presented a condition and matching escalation, not predatory seizure."},{id:"observe",label:"Stop escalating and look for a change of method",feedback:"This preserves strength and creates room for a different response."}],correct:"observe",repair:"Use the new evidence: when scale is mirrored, change the method rather than adding more force.",resolution:"Hanumān becomes small, fulfills the condition, and continues without wasting strength.",secondStep:{prompt:"The challenge still requires him to pass through. What revision uses the opening?",choices:[{id:"small",label:"Become small, enter and exit, then resume the mission",feedback:"Adaptability fulfills the condition without surrendering the route."},{id:"larger",label:"Return to growing larger",feedback:"That restarts the same unproductive escalation."},{id:"retreat",label:"Abandon the crossing",feedback:"The mission remains possible; the failed method needs revision, not the destination."}],correct:"small"}},
 "HJ-07":{verb:"Diagnose",question:"What makes this loss of momentum different from Maināka and Surasā?",evidence:["Hanumān’s speed falls without his consent.","His shadow and movement are seized from below.","The pull is predatory and prevents forward motion.","No welcome or satisfiable test is offered."],choices:[{id:"offer",label:"Treat it like Maināka’s offer",feedback:"Maināka offered rest. Here Hanumān’s movement is taken without consent."},{id:"test",label:"Treat it like Surasā’s test",feedback:"Surasā’s condition could be fulfilled. This seizure gives no path through."},{id:"threat",label:"Recognize a direct threat and confront it",feedback:"The evidence supports decisive action against a predatory obstruction."}],correct:"threat",repair:"Compare the decisive evidence: offer, satisfiable condition, or involuntary predatory seizure.",resolution:"Discernment now calls for force. Hanumān overcomes Siṃhikā and restores the route."},
 "HJ-08":{verb:"Interpret",question:"What response preserves the mission at Laṅkā’s threshold?",evidence:["A guardian prevents entry.","The city beyond remains unknown.","Finding Sītā requires concealment.","The guardian can be overcome without turning arrival into open war."],choices:[{id:"maximum",label:"Use maximum force and announce the arrival",feedback:"Entry would be gained at the cost of secrecy and proportionality."},{id:"retreat",label:"Retreat because any resistance invalidates the mission",feedback:"The destination has been reached; the obstacle calls for a measured response."},{id:"measured",label:"Use enough force to enter, then interpret what the threshold reveals",feedback:"This protects entry, secrecy, and proportionate action."}],correct:"measured",repair:"Choose the response that gains entry while preserving the hidden search beyond the gate.",resolution:"The crossing ends at a meaningful threshold. Movement now becomes infiltration."},
};

export function CrossingTrail({nodeId}:{nodeId:string}){
 const {progress}=useProgress();
 const visible=useMemo(()=>crossingTrailEntries.filter(entry=>entry.id===nodeId||progress.completedNodes.includes(entry.id)),[nodeId,progress.completedNodes]);
 return <aside className={styles.trail} aria-label="Crossing Trail"><header><Footprints/><div><small>Chapter III · evolving response record</small><h3>Crossing Trail</h3></div></header><ol>{visible.map((entry,index)=>{const resolved=progress.completedNodes.includes(entry.id)||Boolean(progress.crossingTrailAnswers[entry.id]);return <li key={entry.id} data-resolved={resolved}><span>{resolved?<Check/>:index+1}</span><div><strong>{entry.title}</strong><small>{resolved?entry.response:"Reading the obstacle…"}</small>{resolved&&<p>{entry.principle}</p>}</div></li>})}</ol></aside>;
}

export function CrossingExplore({node,onComplete}:{node:JourneyNode;onComplete:()=>void}){
 const {progress,saveCrossingTrailAnswer}=useProgress(),action=actions[node.id],stored=progress.crossingTrailAnswers[node.id];
 const [choice,setChoice]=useState(""),[checked,setChecked]=useState(false),[repairing,setRepairing]=useState(false),[second,setSecond]=useState("");
 const firstCorrect=choice===action.correct,secondCorrect=!action.secondStep||second===action.secondStep.correct,complete=Boolean(stored)||(firstCorrect&&secondCorrect);
 function check(){setChecked(true);if(firstCorrect&&secondCorrect)saveCrossingTrailAnswer(node.id,`${choice}${second?`:${second}`:""}`);}
 function revise(){setRepairing(true);setChecked(false);setChoice("");setSecond("");}
 return <div className={styles.experience}><CrossingTrail nodeId={node.id}/><section className={styles.action} aria-labelledby="crossing-action-title"><p className="eyebrow"><Shield/> {action.verb} · read before responding</p><h2 id="crossing-action-title">{action.question}</h2><div className={styles.evidence}><h3>What the scene establishes</h3><ul>{action.evidence.map(item=><li key={item}>{item}</li>)}</ul></div><fieldset><legend>Choose the response that best preserves the mission</legend>{action.choices.map(item=><label key={item.id}><input type="radio" name={`${node.id}-response`} value={item.id} checked={choice===item.id} onChange={()=>{setChoice(item.id);setChecked(false);}} disabled={Boolean(stored)}/><span>{item.label}</span></label>)}</fieldset>
  {action.secondStep&&firstCorrect&&<fieldset className={styles.second}><legend>{action.secondStep.prompt}</legend>{action.secondStep.choices.map(item=><label key={item.id}><input type="radio" name={`${node.id}-revision`} value={item.id} checked={second===item.id} onChange={()=>{setSecond(item.id);setChecked(false);}} disabled={Boolean(stored)}/><span>{item.label}</span></label>)}</fieldset>}
  {checked&&!complete&&<div className={styles.feedback} role="status"><Lightbulb/><div><strong>Read the decisive evidence again</strong><p>{choice?([...action.choices,...(action.secondStep?.choices??[])].find(item=>item.id===(firstCorrect?second:choice))?.feedback):action.repair}</p></div></div>}
  {repairing&&!complete&&<div className={styles.repair} role="status"><RefreshCcw/><p>{action.repair}</p></div>}
  {complete&&<div className={styles.success} role="status"><Check/><div><strong>Response principle recorded</strong><p>{action.resolution}</p></div></div>}
  <div className={styles.buttons}>{!complete&&<button type="button" onClick={check} disabled={!choice||(Boolean(action.secondStep)&&firstCorrect&&!second)}>Commit response</button>}{checked&&!complete&&<button type="button" className={styles.secondary} onClick={revise}>Revise using evidence</button>}{complete&&<button type="button" onClick={onComplete}>See the canonical story <ArrowRight/></button>}</div>
 </section></div>;
}
