"use client";
import {useState} from "react";
import type {ReactNode} from "react";
import {ArrowDown,BookOpen,Check,Eye,EyeOff,Gem,Lightbulb,Link2,Sparkles,UserRoundSearch} from "lucide-react";
import {CharacterPortrait} from "@/components/character-portrait";
import {SacredObjectCard} from "@/components/sacred-object-card";
import {useProgress} from "@/components/progress-provider";
import {characters} from "@/data/discoveries";
import {discoveryKey,sacredObjectById} from "@/data/encounter-activities";
import {relationships} from "@/data/relationships";
import type {CharacterUnlockActivity,DiscoveryHotspot as DiscoveryHotspotData,EncounterActivity,JourneyNode,ObjectDiscoveryActivity,PredictionChoiceActivity,RelationshipUnlockActivity,SceneDiscoveryActivity,StoryMemoryActivity} from "@/lib/types";
import styles from "@/components/encounter-activities.module.scss";

export function EncounterActivities({node,activities:provided,compact=false}:{node:JourneyNode;activities?:EncounterActivity[];compact?:boolean}){const activities=(provided??node.activities??[]).filter(activity=>!(activity.type==="sceneDiscovery"&&activity.embedded));if(!activities.length)return null;return <section className={`${styles.section} ${compact?styles.compactSection:""}`}>{!compact&&<header><p className="eyebrow">Explore · predict · discover</p><h2>Enter the living scene</h2><p>These interactions reveal the canonical story without changing its outcome. They do not affect mastery stars.</p></header>}<div className={styles.activityStack}>{activities.map(activity=><ActivityRenderer key={activity.id} activity={activity}/>)}</div></section>}
function ActivityRenderer({activity}:{activity:EncounterActivity}){let content:ReactNode;switch(activity.type){case"sceneDiscovery":content=<SceneDiscovery activity={activity}/>;break;case"predictionChoice":content=<PredictionChoice activity={activity}/>;break;case"characterUnlock":content=<CharacterUnlock activity={activity}/>;break;case"relationshipUnlock":content=<RelationshipUnlock activity={activity}/>;break;case"objectDiscovery":content=<ObjectDiscovery activity={activity}/>;break;case"storyMemory":content=<StoryMemory activity={activity}/>;break;case"masteryQuestion":return null;}return <div className={styles.activityWrap}>{content}<div className={styles.sourceStrip}><span>{activity.claimType.replace(/([A-Z])/g," $1")}</span>{activity.sources.map(source=><strong key={source}>{source}</strong>)}</div></div>}

export function SceneDiscovery({activity}:{activity:SceneDiscoveryActivity}){const {progress,discoverScene}=useProgress();const found=activity.hotspots.filter(hotspot=>progress.sceneDiscoveries.includes(discoveryKey(activity.id,hotspot.id)));return <article className={`${styles.activityCard} ${activity.hidden?styles.hiddenCard:""}`}><div className={styles.activityHeading}>{activity.hidden?<EyeOff/>:<Eye/>}<div><p className="eyebrow">{activity.optional?"Optional discovery":"Scene discovery"}</p><h3>{activity.hidden&&found.length===0?"Something remains unseen":activity.title}</h3></div><DiscoveryProgress found={found.length} total={activity.hotspots.length}/></div><p>{activity.prompt}</p><div className={styles.hotspots}>{activity.hotspots.map(hotspot=><DiscoveryHotspot key={hotspot.id} hotspot={hotspot} hidden={Boolean(activity.hidden)} revealed={found.includes(hotspot)} onDiscover={()=>discoverScene(activity.id,hotspot.id)}/>)}</div>{found.length===activity.hotspots.length&&<DiscoveryReveal text={activity.optional?"Optional discovery found. The main story remains unchanged.":"Scene explored. Its story details are now part of your journey record."}/>}</article>}
export function DiscoveryHotspot({hotspot,hidden,revealed,onDiscover}:{hotspot:DiscoveryHotspotData;hidden:boolean;revealed:boolean;onDiscover:()=>void}){return <button className={revealed?styles.revealedHotspot:""} onClick={onDiscover}><span>{revealed?<Check/>:<Sparkles/>}</span><strong>{revealed?hotspot.label:hidden?"Search gently":hotspot.label}</strong>{revealed&&<small>{hotspot.detail}</small>}</button>}
export function DiscoveryProgress({found,total}:{found:number;total:number}){return <span className={styles.discoveryProgress}>Discoveries <strong>{found}/{total}</strong></span>}
export function DiscoveryReveal({text}:{text:string}){return <div className={styles.discoveryReveal}><Sparkles/><span>{text}</span></div>}

function PredictionChoice({activity}:{activity:PredictionChoiceActivity}){const {progress,selectPrediction}=useProgress(),selected=progress.predictionChoices[activity.id];return <article className={styles.activityCard}><div className={styles.activityHeading}><Lightbulb/><div><p className="eyebrow">Prediction · learning adaptation</p><h3>{activity.title}</h3></div></div><p className={styles.prompt}>{activity.prompt}</p><div className={styles.predictionChoices}>{activity.choices.map(choice=><button key={choice.id} disabled={Boolean(selected)} className={selected===choice.id?styles.chosenPrediction:""} onClick={()=>selectPrediction(activity.id,choice.id)}>{choice.label}</button>)}</div>{selected&&<div className={styles.canonicalReveal}><div><span>Your choice</span><strong>{activity.choices.find(choice=>choice.id===selected)?.label}</strong></div><ArrowDown/><div><span>What Hanumān did</span><strong>{activity.canonicalReveal}</strong><p>{activity.explanation}</p></div><small>The prediction is an interactive reflection. The canonical narrative does not change.</small></div>}</article>}

function CharacterUnlock({activity}:{activity:CharacterUnlockActivity}){const {progress,discoverScene}=useProgress(),revealed=progress.sceneDiscoveries.includes(activity.id);return <article className={styles.activityCard}><div className={styles.activityHeading}><UserRoundSearch/><div><p className="eyebrow">Character discovery</p><h3>{activity.title}</h3></div></div><p>{activity.description}</p>{!revealed?<button className={styles.revealButton} onClick={()=>discoverScene(activity.id)}>Reveal character</button>:<div className={styles.characterReveals}>{activity.characterNames.map(name=>{const character=characters.find(item=>item.name===name);return <div key={name}><span>{character?.portrait&&<CharacterPortrait name={name} portrait={character.portrait} usage="reward"/>}</span><strong>{name}</strong></div>})}</div>}</article>}
function RelationshipUnlock({activity}:{activity:RelationshipUnlockActivity}){const {progress,discoverScene}=useProgress(),revealed=progress.sceneDiscoveries.includes(activity.id);return <article className={styles.activityCard}><div className={styles.activityHeading}><Link2/><div><p className="eyebrow">Relationship clue</p><h3>{activity.title}</h3></div></div><p>{activity.description}</p>{!revealed?<button className={styles.revealButton} onClick={()=>discoverScene(activity.id)}>Notice the connection</button>:<div className={styles.relationshipReveals}>{activity.relationshipIds.map(id=>{const relationship=relationships.find(item=>item.id===id);if(!relationship)return null;const from=characters.find(c=>c.id===relationship.fromCharacterId),to=characters.find(c=>c.id===relationship.toCharacterId);return <strong key={id}>{from?.name} → {to?.name}<small>{relationship.clue} Solve it in Connections.</small></strong>})}</div>}</article>}
function ObjectDiscovery({activity}:{activity:ObjectDiscoveryActivity}){const {progress,discoverSacredObject}=useProgress(),object=sacredObjectById(activity.objectId),revealed=progress.discoveredObjects.includes(activity.objectId);if(!object)return null;return <article className={`${styles.activityCard} ${styles.objectCard}`}><SacredObjectCard object={object} discovered={revealed} mode="standard" lockedLabel={activity.title} lockedDescription={activity.prompt}/>{!revealed&&<button className={styles.objectReveal} onClick={()=>discoverSacredObject(object.id)}><Gem/>Reveal the story object</button>}</article>}
function StoryMemory({activity}:{activity:StoryMemoryActivity}){const {progress,saveStoryMemory}=useProgress(),saved=progress.storyMemoryAnswers[activity.id]?.split(",").filter(Boolean)??[],[local,setLocal]=useState(saved),complete=local.length===activity.items.length,correct=complete&&local.every((id,index)=>id===activity.correctOrder[index]),choices=[...activity.items.slice(1),activity.items[0]];function add(id:string){if(local.includes(id)||complete)return;const next=[...local,id];setLocal(next);saveStoryMemory(activity.id,next)}function reset(){setLocal([]);saveStoryMemory(activity.id,[])}return <article className={styles.activityCard}><div className={styles.activityHeading}><BookOpen/><div><p className="eyebrow">Story memory</p><h3>{activity.title}</h3></div></div><p className={styles.prompt}>{activity.prompt}</p><div className={styles.memoryPath}>{local.map((id,index)=><span key={id}><strong>{index+1}</strong>{activity.items.find(item=>item.id===id)?.label}</span>)}{Array.from({length:activity.items.length-local.length},(_,index)=><i key={index}>?</i>)}</div><div className={styles.memoryChoices}>{choices.map(item=><button key={item.id} disabled={local.includes(item.id)||complete} onClick={()=>add(item.id)}>{item.label}</button>)}</div>{complete&&<div className={`${styles.memoryFeedback} ${correct?styles.memoryCorrect:""}`}><strong>{correct?"The story is in order":"The path needs another look"}</strong><p>{correct?activity.explanation:"Reset the sequence and follow the direction of the journey."}</p>{!correct&&<button onClick={reset}>Reset sequence</button>}</div>}</article>}
