"use client";
import {ArrowDown,ArrowUp,Check,Compass,Eye,Lightbulb,Shuffle} from "lucide-react";
import {cn} from "@/lib/utils";
import type {MasteryActivity} from "@/lib/types";
import styles from "@/components/journey.module.scss";

export function MasteryActivityRenderer({activity,response,onChange,revealed}:{activity:MasteryActivity;response:string;onChange:(value:string)=>void;revealed:boolean}){
 return <div className={styles.masteryActivity} data-activity-type={activity.type}><div className={styles.activityType}><ActivityIcon type={activity.type}/><span>{label(activity.type)}</span></div>{activity.type==="sourceComparison"&&<p className={styles.connectionEndpoints}>{activity.comparisonContext}</p>}<p className={styles.activityPrompt}>{activity.prompt}</p>{activity.type==="connectionBuilder"?<ConnectionMastery activity={activity} response={response} onChange={onChange} revealed={revealed}/>:activity.type==="multiSelect"?<Multi activity={activity} response={response} onChange={onChange} revealed={revealed}/>:activity.type==="sequence"?<Sequence activity={activity} response={response} onChange={onChange} revealed={revealed}/>:activity.type==="matching"?<Matching activity={activity} response={response} onChange={onChange} revealed={revealed}/>:<Single activity={activity} response={response} onChange={onChange} revealed={revealed}/>}<details className={styles.masteryHint}><summary><Lightbulb/>Need a hint?</summary><p>{activity.hint}</p></details></div>;
}
function Single({activity,response,onChange,revealed}:{activity:Extract<MasteryActivity,{type:"singleSelect"|"sceneDiscovery"|"predictionChoice"|"sourceComparison"}>;response:string;onChange:(value:string)=>void;revealed:boolean}){return <div className={cn(styles.answerChoices,activity.type==="sceneDiscovery"&&styles.sceneChoices)}>{activity.type==="predictionChoice"&&<p className={styles.predictionNote}>Make a prediction, then compare it with the canonical action. The story itself does not change.</p>}{activity.options.map(choice=><button key={choice.id} disabled={revealed} onClick={()=>onChange(choice.id)} className={cn(response===choice.id&&styles.answerSelected,revealed&&choice.id===activity.correctAnswer&&styles.answerCorrect,revealed&&response===choice.id&&response!==activity.correctAnswer&&styles.answerWrong)}>{activity.type==="sceneDiscovery"?<Eye/>:<span>{choice.id.toUpperCase()}</span>}{choice.label}</button>)}</div>}
function Multi({activity,response,onChange,revealed}:{activity:Extract<MasteryActivity,{type:"multiSelect"}>;response:string;onChange:(value:string)=>void;revealed:boolean}){const selected=response.split(",").filter(Boolean);function toggle(id:string){const next=selected.includes(id)?selected.filter(item=>item!==id):[...selected,id];onChange(next.join(","));}return <fieldset className={styles.multiChoices}><legend>Select all that apply</legend>{activity.options.map(choice=><button type="button" aria-pressed={selected.includes(choice.id)} key={choice.id} disabled={revealed} onClick={()=>toggle(choice.id)}><span>{selected.includes(choice.id)&&<Check/>}</span>{choice.label}</button>)}</fieldset>}
function Sequence({activity,response,onChange,revealed}:{activity:Extract<MasteryActivity,{type:"sequence"}>;response:string;onChange:(value:string)=>void;revealed:boolean}){const ids=response.split(",").filter(Boolean),ordered=(ids.length?ids:activity.items.map(item=>item.id));function move(index:number,delta:number){const target=index+delta;if(target<0||target>=ordered.length)return;const next=[...ordered];[next[index],next[target]]=[next[target],next[index]];onChange(next.join(","));}return <ol className={styles.sequenceChoices}>{ordered.map((id,index)=><li key={id}><strong>{index+1}</strong><span>{activity.items.find(item=>item.id===id)?.label}</span><div><button disabled={revealed||index===0} onClick={()=>move(index,-1)} aria-label={`Move ${activity.items.find(item=>item.id===id)?.label} earlier`}><ArrowUp/></button><button disabled={revealed||index===ordered.length-1} onClick={()=>move(index,1)} aria-label={`Move ${activity.items.find(item=>item.id===id)?.label} later`}><ArrowDown/></button></div></li>)}</ol>}
function Matching({activity,response,onChange,revealed}:{activity:Extract<MasteryActivity,{type:"matching"}>;response:string;onChange:(value:string)=>void;revealed:boolean}){const state=Object.fromEntries(response.split(";").filter(Boolean).map(item=>item.split("=")));function set(id:string,value:string){const next={...state,[id]:value};onChange(activity.pairs.filter(pair=>next[pair.id]).map(pair=>`${pair.id}=${next[pair.id]}`).join(";"));}return <div className={styles.matchingChoices}>{activity.pairs.map(pair=><label key={pair.id}><span>{pair.left}</span><select value={state[pair.id]??""} disabled={revealed} onChange={event=>set(pair.id,event.target.value)}><option value="">Choose a match…</option>{activity.options.map(option=><option value={option.id} key={option.id}>{option.label}</option>)}</select></label>)}</div>}
function ActivityIcon({type}:{type:MasteryActivity["type"]}){return type==="sequence"?<Shuffle/>:type==="sceneDiscovery"?<Compass/>:type==="predictionChoice"?<Lightbulb/>:<Check/>}
function label(type:MasteryActivity["type"]){return({sourceComparison:"Compare the source episodes",connectionBuilder:"Build a connection",singleSelect:"Choose one",multiSelect:"Select all",sequence:"Story sequence",matching:"Match the story",sceneDiscovery:"Scene discovery",predictionChoice:"Prediction and reveal"} as Record<string,string>)[type]??type;}

function ConnectionMastery({activity,response,onChange,revealed}:{activity:Extract<MasteryActivity,{type:"connectionBuilder"}>;response:string;onChange:(value:string)=>void;revealed:boolean}){
 const selected=activity.options.find(o=>o.id===response);
 return <div className={styles.connectionMastery}>{activity.connectionContext&&<p className={styles.connectionEndpoints}>{activity.connectionContext}</p>}<label>Choose the bond to build<select aria-label="Relationship to build" value={response} disabled={revealed} onChange={event=>onChange(event.target.value)}><option value="">Choose a connection…</option>{activity.options.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select></label>{selected&&<div role="status" className={styles.connectionPreview}>{activity.connectionContext&&<span>{activity.connectionContext}</span>}<strong>{selected.label}</strong><small>{revealed&&response===activity.correctAnswer?"Connection built and added to your network":"Proposed connection · check your response"}</small></div>}</div>;
}
