"use client";
import {useMemo,useState} from "react";
import {Check,CircleHelp,Network,RotateCcw,Sparkles} from "lucide-react";
import {useProgress} from "@/components/progress-provider";
import {CharacterPortrait} from "@/components/character-portrait";
import {characters} from "@/data/discoveries";
import {availableRelationshipChallenges,correctRelationshipAnswers,relationshipChallengeLevels} from "@/data/relationship-challenges";
import {characterNameById} from "@/data/character-ids";
import {relationshipTypeLabels,relationships} from "@/data/relationships";
import type {Difficulty} from "@/lib/types";
import styles from "@/app/connections/connections.module.scss";
const levels:Difficulty[]=["explorer","seeker","scholar"];
export function RelationshipChallengeGame(){
 const {progress,answerConnection}=useProgress();const [level,setLevel]=useState<Difficulty>("explorer"),[cursor,setCursor]=useState(0),[selected,setSelected]=useState("");
 const available=useMemo(()=>availableRelationshipChallenges(progress.unlockedRelationships).filter(c=>c.difficulty===level),[progress.unlockedRelationships,level]);const challenge=available[cursor%Math.max(available.length,1)],stored=challenge?progress.relationshipChallengeAnswers[challenge.id]:"",answer=selected||stored,answered=Boolean(answer),correct=challenge?.answer===answer;
 function choose(value:string){if(!challenge)return;setSelected(value);answerConnection(challenge.id,value);}function next(){setSelected("");setCursor(value=>(value+1)%Math.max(available.length,1));}
 return <div className={styles.playLayout}><aside className={styles.levelRail}><p className="eyebrow">Learning path</p>{levels.map(item=><button key={item} className={level===item?styles.activeLevel:""} onClick={()=>{setLevel(item);setCursor(0);setSelected("");}}><span>{item==="explorer"?"I":item==="seeker"?"II":"III"}</span><div><strong>{item}</strong><small>{relationshipChallengeLevels[item]}</small></div></button>)}<div className={styles.mastery}><Sparkles/><strong>{correctRelationshipAnswers(progress.relationshipChallengeAnswers).length}</strong><span>connections understood</span></div></aside><section className={styles.challengeCard}>{challenge?<><div className={styles.challengeTop}><span>{level} challenge · {cursor%available.length+1} of {available.length}</span><CircleHelp/></div><h2>{challenge.prompt}</h2><p>{challenge.context}</p><div className={styles.options}>{challenge.options.map(option=><button key={option.id} onClick={()=>choose(option.id)} className={answer===option.id?(correct?styles.correct:styles.incorrect):""} disabled={answered&&correct}><span>{option.label}</span>{answer===option.id&&correct&&<Check/>}</button>)}</div>{answered&&<div className={`${styles.feedback} ${correct?styles.feedbackCorrect:""}`} aria-live="polite"><strong>{correct?"Connection understood":"Look again"}</strong><p>{correct?challenge.explanation:"That choice does not fit this event. Review the direction and the story clue, then choose again."}</p></div>}{correct&&<ConfirmedRelationship relationshipId={challenge.relationshipIds[0]}/>}<button className={styles.nextButton} onClick={next}>{correct?"Next connection":"Another connection"}<RotateCcw size={16}/></button></>:<div className={styles.empty}><Network/><h2>No {level} challenge is open yet</h2><p>Continue Hanumān’s journey to reveal the relationships needed for this level.</p></div>}</section><ConnectionBuilder unlockedIds={progress.unlockedRelationships}/></div>;
}
function ConfirmedRelationship({relationshipId}:{relationshipId:string}){const relationship=relationships.find(item=>item.id===relationshipId);if(!relationship)return null;const from=characters.find(item=>item.id===relationship.fromCharacterId),to=characters.find(item=>item.id===relationship.toCharacterId);if(!from||!to)return null;return <div className={styles.confirmedVisual}><span className={styles.confirmedPerson}><span className={styles.confirmedPortrait}>{from.portrait&&<CharacterPortrait name={from.name} portrait={from.portrait} usage="medallion"/>}</span><strong>{from.name}</strong></span><span className={styles.confirmedBond}><Check/><span>{relationshipTypeLabels[relationship.type]}</span></span><span className={styles.confirmedPerson}><span className={styles.confirmedPortrait}>{to.portrait&&<CharacterPortrait name={to.name} portrait={to.portrait} usage="medallion"/>}</span><strong>{to.name}</strong></span></div>}
function ConnectionBuilder({unlockedIds}:{unlockedIds:string[]}){const unlocked=relationships.filter(r=>unlockedIds.includes(r.id)),ids=Array.from(new Set(unlocked.flatMap(r=>[r.fromCharacterId,r.toCharacterId]))),[from,setFrom]=useState(ids[0]??""),[to,setTo]=useState(ids[1]??""),[type,setType]=useState("guidance"),[result,setResult]=useState<"idle"|"right"|"wrong">("idle");if(ids.length<2)return null;return <section className={styles.builder}><div><p className="eyebrow">Build a connection</p><h2>Select → connect → understand</h2><p>This tap-friendly mode works without dragging nodes.</p></div><div className={styles.builderFields}><label>From<select value={from} onChange={e=>{setFrom(e.target.value);setResult("idle");}}>{ids.map(id=><option key={id} value={id}>{characterNameById[id]}</option>)}</select></label><span>→</span><label>To<select value={to} onChange={e=>{setTo(e.target.value);setResult("idle");}}>{ids.map(id=><option key={id} value={id}>{characterNameById[id]}</option>)}</select></label><label>Relationship<select value={type} onChange={e=>{setType(e.target.value);setResult("idle");}}>{Object.entries(relationshipTypeLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><button onClick={()=>setResult(unlocked.some(r=>r.fromCharacterId===from&&r.toCharacterId===to&&r.type===type)?"right":"wrong")}>Check connection</button></div>{result!=="idle"&&<p className={result==="right"?styles.builderRight:styles.builderWrong}>{result==="right"?"Yes — that directed connection is part of your discovered network.":"That exact direction and relationship have not been discovered. Try reversing the characters or choosing another bond."}</p>}</section>}
